# Generated by Django 3.2.4 on 2021-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=256)),
                ('pageCount', models.IntegerField(default=0, max_length=20)),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
                ('thumbnailUrl', models.CharField(max_length=256, null=True)),
                ('shortDescription', models.CharField(max_length=512, null=True)),
                ('longDescription', models.TextField(null=True)),
                ('status', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=256)),
                ('categories', models.CharField(max_length=256)),
            ],
        ),
    ]
