# Generated by Django 3.2.4 on 2021-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_pagecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
