# Generated by Django 3.2.4 on 2021-07-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
